import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react';
import FileUpload from './FileUpload'

async function Tempupload() {
  var res = await fetch('api/hello');
  var data = await res.json();
  document.getElementById("l1").innerHTML = data;
}

async function Tempdownload() {
  var d = document.getElementById('t1').value;
  var res = await fetch('api/filedownload', {
    method: 'POST',
    body: JSON.stringify({d}),
    headers: {
      'Content-Type' : 'application/json',
    }
  });
  var data = await res.json();
  document.getElementById("l1").innerHTML = data;
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to SpaceChain
        </h1>

        <br></br>
        <FileUpload></FileUpload>
        
        <br></br><br></br>
        <label className={styles.label} id='l1'></label>
        <br></br><br></br>
        <label style={{fontSize: "25px", paddingBottom: "20px", color: "white"}}>Enter CID</label>
        <input type = "text" id="t1" className={styles.label}></input>
        <div className={styles.grid} style={{paddingTop: "50px"}}>
        <button onClick={Tempupload} className={styles.button}>Upload</button>
        <button onClick={Tempdownload} className={styles.button}>Download</button>
        </div>

      </main>

      <footer className={styles.footer}>
        <h3>Team SpaceChain</h3>
      </footer>
    </div>
  )
}